# Custom Language File for Launcher Customizer

[ejs.app]
title = "Nok Craft Launcher"

[ejs.landing]
mediaGitHubURL = "https://github.com/nocilex41/NokCraftLaunch"
mediaTwitterURL = "#"
mediaInstagramURL = "#"
mediaYouTubeURL = "#"
mediaDiscordURL = "https://discord.gg/zNWUXdt"

[ejs.settings]
sourceGithubLink = "https://github.com/nocilex41/NokCraftLaunch"
supportLink = "https://github.com/nocilex41/NokCraftLaunch/issues"

[ejs.welcome]
welcomeHeader = "BIENVENUE SUR NOK CRAFT"
welcomeDescription = "Flemme de la descriot"
welcomeDescCTA = "You are just a few clicks away from NokCraft."
